/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.4/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.jmh.core)
    annotationProcessor(libs.jmh.annotationProcessor)
    implementation(libs.junit.jupiterApi)
    implementation(libs.log4j.core)
    implementation(libs.jackson.databind)
    implementation(libs.bouncycastle.cryptoProvider)
    implementation(libs.bouncycastle.pkix)
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.jar {
    archiveBaseName = "benchmarks"
    manifest { attributes("Main-Class" to "benchmark.Benchmarks") }
    from(configurations.runtimeClasspath.get()
        .filter { it.name.endsWith(".jar") }.map { zipTree(it) })
        .exclude("META-INF/BC2048KE.SF")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
