/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.4/userguide/building_swift_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "crypto"

dependencyResolutionManagement.versionCatalogs.create("libs") {
    library("jmh-core", "org.openjdk.jmh:jmh-core:1.37")
    library("jmh-annotationProcessor", "org.openjdk.jmh:jmh-generator-annprocess:1.37")
    library("junit-jupiterApi", "org.junit.jupiter:junit-jupiter-api:5.10.2")
    library("log4j-core", "org.apache.logging.log4j:log4j-core:2.23.1")
    library("jackson-databind", "com.fasterxml.jackson.core:jackson-databind:2.17.0")
    library("bouncycastle.cryptoProvider", "org.bouncycastle:bcprov-jdk18on:1.78.1")
    library("bouncycastle.pkix", "org.bouncycastle:bcpkix-jdk18on:1.78.1")
}
